name: convex_dart_builder
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  analyzer: ^7.7.1
  build: ^3.1.0
  build_runner: ^2.7.1
  build_runner_core: ^9.3.1
  collection: ^1.19.1
  convex_dart:
  dart_mappable: ^4.6.0
  dart_style: ^3.1.1
  path: ^1.9.1
  recase: ^4.1.0
  source_gen: ^3.1.0

dev_dependencies:
  dart_mappable_builder: ^4.6.0
  lints: ^6.0.0

resolution: workspace
