name: _
publish_to: none
environment:
  sdk: ^3.8.0
workspace:
  - convex_dart
  - convex_dart_builder
  - example
  - example/api

dependency_overrides:
  dart_mappable_builder:
    git:
      url: https://github.com/dickermoshe/dart_mappable
      ref: main
      path: packages/dart_mappable_builder
