// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'base_client/query_result.dart';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'value.dart';
part 'dart.freezed.dart';

            // These functions are ignored because they are not marked as `pub`: `connected_client`, `handle_direct_function_result`, `internal_action`, `internal_clear_auth`, `internal_mutation`, `internal_set_auth_callback`, `internal_set_auth`, `internal_subscribe`, `new`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`


            BTreeMapStringValue  hashmapToBtreemap({required Map<String, Value> hashmap }) => RustLib.instance.api.crateDartHashmapToBtreemap(hashmap: hashmap);

Map<String, Value>  btreemapToHashmap({required BTreeMapStringValue btreemap }) => RustLib.instance.api.crateDartBtreemapToHashmap(btreemap: btreemap);

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DartQuerySubscriber>>
                abstract class DartQuerySubscriber implements RustOpaqueInterface, QuerySubscriber {
                    factory DartQuerySubscriber({required BoxFnFunctionResultDartFnFutureResult onUpdate })=>RustLib.instance.api.crateDartDartQuerySubscriberNew(onUpdate: onUpdate);


 Future<void>  onUpdate({required FunctionResult value });



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MobileConvexClient>>
                abstract class MobileConvexClient implements RustOpaqueInterface {
                    /// Executes an action on the Convex backend.
 Future<Value>  action({required String name , required BTreeMapStringValue args });


/// Clear the auth token callback, effectively logging out.
 Future<void>  clearAuth();


/// Executes a mutation on the Convex backend.
 Future<Value>  mutation({required String name , required BTreeMapStringValue args });


/// Creates a new [MobileConvexClient].
///
/// The internal [ConvexClient] doesn't get created/connected until the
/// first public method call that hits the Convex backend.
///
/// The `client_id` should be a string representing the name and version of
/// the foreign client.
factory MobileConvexClient({required String deploymentUrl , required String clientId })=>RustLib.instance.api.crateDartMobileConvexClientNew(deploymentUrl: deploymentUrl, clientId: clientId);


/// Executes a query on the Convex backend.
 Future<Value>  query({required String name , required BTreeMapStringValue args });


/// Provide an OpenID Connect ID token to be associated with this client.
///
/// Doing so will share that information with the Convex backend and a valid
/// token will give the backend knowledge of a logged in user.
///
/// Passing [None] for the token will disassociate a previous token,
/// effectively returning to a logged out state.
 Future<void>  setAuth({String? token });


/// Set an auth token fetcher callback.
///
/// The callback is invoked immediately and again on every websocket
/// reconnect, allowing dynamic token refresh.
///
/// Passing a function that returns [None] clears auth (logs out).
 Future<void>  setAuthCallback({required FutureOr<String?> Function(bool) fetchToken });


/// Subscribe to updates to a query against the Convex backend.
///
/// The [QuerySubscriber] will be called back with initial query results and
/// it will continue to get called as the underlying data changes.
///
/// The returned [SubscriptionHandle] can be used to cancel the
/// subscription.
 Future<SubscriptionHandle>  subscribe({required String name , required BTreeMapStringValue args , required FutureOr<void> Function(FunctionResult) onUpdate });



                    
                }
                


                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SubscriptionHandle>>
                abstract class SubscriptionHandle implements RustOpaqueInterface {
                    /// Cancels the subscription by sending a cancellation signal.
 void  cancel();



                    
                }
                


                abstract class QuerySubscriber {
                    /// Called when a new update is received
 Future<void>  onUpdate({required FunctionResult value });


                }
                

@freezed
                sealed class ClientError with _$ClientError implements FrbException {
                    const ClientError._();

                     /// An internal error within the mobile Convex client.
const factory ClientError.internalError({ /// A generic error message from the server.
  required String msg , }) = ClientError_InternalError;
 /// An application-specific error from a remote Convex backend function.
const factory ClientError.convexError({ /// The ConvexError passed from the server to the client.
  required ConvexError err , }) = ClientError_ConvexError;
 /// An unexpected server-side error from a remote Convex function.
const factory ClientError.serverError({ /// A generic error message from the server.
  required String msg , }) = ClientError_ServerError;

                    

                    
                }
            