// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'base_client/query_result.dart';
import 'dart.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'value.dart';
import 'value/json/bytes.dart';
import 'value/json/float.dart';
import 'value/json/integer.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_BTreeMapStringValuePtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValuePtr;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_DartQuerySubscriberPtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriberPtr;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_JsonValuePtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValuePtr;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MobileConvexClientPtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClientPtr;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_SubscriptionHandlePtr => wire._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandlePtr;



                  @protected AnyhowException dco_decode_AnyhowException(dynamic raw);

@protected BTreeMapStringValue dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue(dynamic raw);

@protected DartQuerySubscriber dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber(dynamic raw);

@protected JsonValue dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue(dynamic raw);

@protected MobileConvexClient dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient(dynamic raw);

@protected SubscriptionHandle dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle(dynamic raw);

@protected DartQuerySubscriber dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber(dynamic raw);

@protected MobileConvexClient dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient(dynamic raw);

@protected SubscriptionHandle dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle(dynamic raw);

@protected FutureOr<void> Function(FunctionResult) dco_decode_DartFn_Inputs_function_result_Output_unit_AnyhowException(dynamic raw);

@protected Object dco_decode_DartOpaque(dynamic raw);

@protected BTreeMapStringValue dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue(dynamic raw);

@protected DartQuerySubscriber dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber(dynamic raw);

@protected JsonValue dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue(dynamic raw);

@protected MobileConvexClient dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient(dynamic raw);

@protected SubscriptionHandle dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle(dynamic raw);

@protected String dco_decode_String(dynamic raw);

@protected QuerySubscriber dco_decode_TraitDef_QuerySubscriber(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected ConvexError dco_decode_box_autoadd_convex_error(dynamic raw);

@protected FunctionResult dco_decode_box_autoadd_function_result(dynamic raw);

@protected Value dco_decode_box_autoadd_value(dynamic raw);

@protected ClientError dco_decode_client_error(dynamic raw);

@protected ConvexError dco_decode_convex_error(dynamic raw);

@protected double dco_decode_f_64(dynamic raw);

@protected FunctionResult dco_decode_function_result(dynamic raw);

@protected PlatformInt64 dco_decode_i_64(dynamic raw);

@protected PlatformInt64 dco_decode_isize(dynamic raw);

@protected JsonBytes dco_decode_json_bytes(dynamic raw);

@protected JsonFloat dco_decode_json_float(dynamic raw);

@protected JsonInteger dco_decode_json_integer(dynamic raw);

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected List<Value> dco_decode_list_value(dynamic raw);

@protected String? dco_decode_opt_String(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected BigInt dco_decode_usize(dynamic raw);

@protected Value dco_decode_value(dynamic raw);

@protected AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

@protected BTreeMapStringValue sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue(SseDeserializer deserializer);

@protected DartQuerySubscriber sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber(SseDeserializer deserializer);

@protected JsonValue sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue(SseDeserializer deserializer);

@protected MobileConvexClient sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient(SseDeserializer deserializer);

@protected SubscriptionHandle sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle(SseDeserializer deserializer);

@protected DartQuerySubscriber sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber(SseDeserializer deserializer);

@protected MobileConvexClient sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient(SseDeserializer deserializer);

@protected SubscriptionHandle sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle(SseDeserializer deserializer);

@protected Object sse_decode_DartOpaque(SseDeserializer deserializer);

@protected BTreeMapStringValue sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue(SseDeserializer deserializer);

@protected DartQuerySubscriber sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber(SseDeserializer deserializer);

@protected JsonValue sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue(SseDeserializer deserializer);

@protected MobileConvexClient sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient(SseDeserializer deserializer);

@protected SubscriptionHandle sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle(SseDeserializer deserializer);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected ConvexError sse_decode_box_autoadd_convex_error(SseDeserializer deserializer);

@protected FunctionResult sse_decode_box_autoadd_function_result(SseDeserializer deserializer);

@protected Value sse_decode_box_autoadd_value(SseDeserializer deserializer);

@protected ClientError sse_decode_client_error(SseDeserializer deserializer);

@protected ConvexError sse_decode_convex_error(SseDeserializer deserializer);

@protected double sse_decode_f_64(SseDeserializer deserializer);

@protected FunctionResult sse_decode_function_result(SseDeserializer deserializer);

@protected PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

@protected PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

@protected JsonBytes sse_decode_json_bytes(SseDeserializer deserializer);

@protected JsonFloat sse_decode_json_float(SseDeserializer deserializer);

@protected JsonInteger sse_decode_json_integer(SseDeserializer deserializer);

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected List<Value> sse_decode_list_value(SseDeserializer deserializer);

@protected String? sse_decode_opt_String(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected BigInt sse_decode_usize(SseDeserializer deserializer);

@protected Value sse_decode_value(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected void sse_encode_AnyhowException(AnyhowException self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue(BTreeMapStringValue self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber(DartQuerySubscriber self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue(JsonValue self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient(MobileConvexClient self, SseSerializer serializer);

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle(SubscriptionHandle self, SseSerializer serializer);

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber(DartQuerySubscriber self, SseSerializer serializer);

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient(MobileConvexClient self, SseSerializer serializer);

@protected void sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle(SubscriptionHandle self, SseSerializer serializer);

@protected void sse_encode_DartFn_Inputs_function_result_Output_unit_AnyhowException(FutureOr<void> Function(FunctionResult) self, SseSerializer serializer);

@protected void sse_encode_DartOpaque(Object self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue(BTreeMapStringValue self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber(DartQuerySubscriber self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue(JsonValue self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient(MobileConvexClient self, SseSerializer serializer);

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle(SubscriptionHandle self, SseSerializer serializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_convex_error(ConvexError self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_function_result(FunctionResult self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_value(Value self, SseSerializer serializer);

@protected void sse_encode_client_error(ClientError self, SseSerializer serializer);

@protected void sse_encode_convex_error(ConvexError self, SseSerializer serializer);

@protected void sse_encode_f_64(double self, SseSerializer serializer);

@protected void sse_encode_function_result(FunctionResult self, SseSerializer serializer);

@protected void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

@protected void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

@protected void sse_encode_json_bytes(JsonBytes self, SseSerializer serializer);

@protected void sse_encode_json_float(JsonFloat self, SseSerializer serializer);

@protected void sse_encode_json_integer(JsonInteger self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_list_value(List<Value> self, SseSerializer serializer);

@protected void sse_encode_opt_String(String? self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);

@protected void sse_encode_usize(BigInt self, SseSerializer serializer);

@protected void sse_encode_value(Value self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);
                }
                


// Section: wire_class


        class RustLibWire implements BaseWire {

            factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
              RustLibWire(lib.ffiDynamicLibrary);
        
            /// Holds the symbol lookup function.
            final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
                _lookup;
  
            /// The symbols are looked up in [dynamicLibrary].
            RustLibWire(ffi.DynamicLibrary dynamicLibrary)
                : _lookup = dynamicLibrary.lookup;

            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValuePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_convex_dart_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValuePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValuePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_convex_dart_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValue = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBTreeMapStringValuePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriberPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_convex_dart_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriberPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriberPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_convex_dart_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriber = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDartQuerySubscriberPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValuePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_convex_dart_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValuePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValuePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_convex_dart_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValue = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJsonValuePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClientPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_convex_dart_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClientPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClientPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_convex_dart_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClient = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMobileConvexClientPtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle(
                ptr,
              );
            }

            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandlePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_convex_dart_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle');
            late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle = _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandlePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
            void rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle(
              ffi.Pointer<ffi.Void> ptr,
            ) {
              return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle(
                ptr,
              );
            }

            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandlePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>('frbgen_convex_dart_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle');
            late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandle = _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSubscriptionHandlePtr.asFunction<void Function(ffi.Pointer<ffi.Void>)>();
            
        }
        