// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ConvexError>>
abstract class ConvexError implements RustOpaqueInterface {
  Value get data;

  String get message;

  set data(Value data);

  set message(String message);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Value>>
abstract class Value implements RustOpaqueInterface {
  /// Converts this value to a JSON value in the `json` export format.
  /// <https://docs.convex.dev/database/types>
  ///
  /// It is possible for distinct Convex values to be serialized to the same
  /// JSON value by this method. For instance, strings and binary values are
  /// both exported as JSON strings. However, it is possible to convert the
  /// exported value back to a unique Convex value if you also have the `Type`
  /// value associated with the original Convex value (see `roundtrip.rs`).
  ///
  /// # Example
  /// ```
  /// use convex::Value;
  /// use serde_json::{
  ///     json,
  ///     Value as JsonValue,
  /// };
  ///
  /// let value = Value::Bytes(vec![0b00000000, 0b00010000, 0b10000011]);
  /// assert_eq!(JsonValue::from(value.clone()), json!({ "$bytes": "ABCD" }));
  /// assert_eq!(value.export(), json!("ABCD"));
  /// ```
  Future<JsonValue> export_();
}
