name: convex_dart
description: A Flutter package for Convex backend integration, enabling developers to interact with Convex services, manage data, and build applications with real-time synchronization.
version: 0.4.0
repository: https://github.com/dickermoshe/convex-dart/tree/master/convex_dart

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.0
  fast_immutable_collections: ^11.0.0
  flutter_rust_bridge: 2.11.1
  freezed_annotation: ^3.0.0
  meta: ^1.0.0
  async: ^2.0.0
  rxdart: ^0.28.0
  synchronized: ^3.4.0
  locked_async: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: ^2.7.0
  ffi: ^2.1.4
  flutter_lints: ^6.0.0
  freezed: ^3.2.0
  watcher: ^1.1.4
  config: ^0.8.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true

resolution: workspace
