name: convex_dart_cli
description: Command-line tool for generating type-safe Dart client code from Convex backend schemas
version: 0.4.0
repository: https://github.com/dickermoshe/convex-dart/tree/master/convex_dart_cli

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.19.1
  dart_mappable: ^4.6.0
  dart_style: ^3.1.1
  path: ^1.9.1
  recase: ^4.1.0
  config: ^0.8.0
  cli_tools: ^0.8.0
  synchronized: ^3.0.0
  cli_util: ^0.4.2
  locked_async: ^0.1.1
  equatable: ^2.0.0

dev_dependencies:
  build_runner: ^2.7.1
  dart_mappable_builder: ^4.6.0
  lints: ^6.0.0
  test: ^1.25.6
resolution: workspace
