name: convex_dart_cli
description: A CLI for convex_dart
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.19.1
  dart_mappable: ^4.6.0
  dart_style: ^3.1.1
  path: ^1.9.1
  recase: ^4.1.0
  config: ^0.8.0
  cli_tools: ^0.8.0
  synchronized: ^3.0.0
  cli_util: ^0.4.2

dev_dependencies:
  build_runner: ^2.7.1
  dart_mappable_builder: ^4.6.0
  lints: ^6.0.0
  test: ^1.25.6
resolution: workspace
