// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Helper functions for encoding `Bytes`s as `String`s.
class JsonBytes {
  const JsonBytes();

  /// Decode a binary string from a string.
  static Uint8List decode({required String s}) =>
      RustLib.instance.api.crateValueJsonBytesJsonBytesDecode(s: s);

  /// Encode a binary string as a string.
  static String encode({required List<int> bytes}) =>
      RustLib.instance.api.crateValueJsonBytesJsonBytesEncode(bytes: bytes);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsonBytes && runtimeType == other.runtimeType;
}
