// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Helper functions for encoding `Int64`s as `String`s.
enum JsonInteger {
  /// Decode an integer from a string.
  static Future<PlatformInt64> decode({required String s}) =>
      RustLib.instance.api.crateValueJsonIntegerJsonIntegerDecode(s: s);

  /// Encode an integer as a string.
  static Future<String> encode({required PlatformInt64 n}) =>
      RustLib.instance.api.crateValueJsonIntegerJsonIntegerEncode(n: n);
}
